#!/usr/bin/env php
<?php

namespace App;

require __DIR__ . "/vendor/autoload.php";

use App\DB\Database;

$db = new Database(__DIR__ . '/./sqlite.db');

$db->exec('CREATE TABLE foo (bar STRING)');
$db->exec("INSERT INTO foo (bar) VALUES ('This is a test')");

$result = $db->query('SELECT bar FROM foo');
var_dump($result->fetchArray());
